apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: service
  namespace: fastapi-app-ns
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
  type: ClusterIP
